trigger:
  - develop
  - master
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
- script: |
    npm install
    npm run test
    npm run build
    npm run dist:lin
  displayName: 'Building wp-edits'
- job: macOS
  trigger:
  - develop
  - master
  pool:
    vmImage: 'macOS-10.13'
  steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
- script: |
    npm install
    npm run test
    npm run build
    npm run dist:mac
  displayName: 'Building wp-edits'
- job: Windows
  trigger:
  - develop
  - master
  pool:
    vmImage: 'vs2017-win2016'
  steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
- script: |
    npm install
    npm run test
    npm run build
    npm run dist:win
  displayName: 'Building wp-edits'

