trigger: 
  - develop
  - master
jobs: 
  - 
    job: Linux
    pool: 
      vmImage: ubuntu-16.04
    steps:
  - 
    displayName: "Install Node.js"
    inputs: 
      versionSpec: 8.x
    task: NodeTool@0
  - 
    displayName: "Building wp-edits"
    script: |
        npm install
        npm run test
        npm run build
        npm run dist:lin
  - 
    job: macOS
    pool: 
      vmImage: macOS-10.13
    steps:
  - 
    displayName: "Install Node.js"
    inputs: 
      versionSpec: 8.x
    task: NodeTool@0
  - 
    displayName: "Building wp-edits"
    script: |
        npm install
        npm run test
        npm run build:mac
  - 
    job: Windows
    pool: 
      vmImage: vs2017-win2016
    steps:
  - 
    displayName: "Install Node.js"
    inputs: 
      versionSpec: 8.x
    task: NodeTool@0
  - 
    displayName: "Building wp-edits"
    script: |
        npm install
        npm run test
        npm run build
        npm run dist:win
